config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  resources :articles
  resources :categories, except: [:delete]

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show edit update]
  before_action :set_category, only: %i[show edit update]

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: 300 }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category has been successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: 300 }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    return if logged_in? && current_user.admin?

    flash[:alert] = 'Only admins can perform that action'
    redirect_to categories_path
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info me-1 text-decoration-none" %>

app/views/categories/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create a new Category</h1>

    <div class="container">
    <%= render 'shared/errors', obj: @category %>

    <%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 bg-info rounded") do |form| %>    
    <div class="row justify-content-center">
        <div class="col-10 justify-content-center">
            <div class="form-group row mt-4">
                <%= form.label :name, "Category name", class: "col-2 col-form-label text-light" %>
                <div class="col-10">
                    <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
                </div>
            </div>

            <div class="form-group mt-3 d-flex justify-content-around">
                <%= form.submit class: "btn btn-outline-light btn-lg" %>
            </div>
        <% end %>
        </div>
    </div>
    <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "d-flex justify-content-around text-info" %>
    </div>
</div>

app/views/categories/index.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Listing all Categories</h1>


    <div class="flickr_pagination">
        <%= will_paginate @categories, :container => false %>
    </div>  
  <div class="container">
    <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
              <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
                edited <%= time_ago_in_words(category.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
  </div>
</div>

app/views/categories/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create a new Category</h1>

    <div class="container">
    <%= render 'shared/errors', obj: @category %>

    <%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 bg-info rounded") do |form| %>    
    <div class="row justify-content-center">
        <div class="col-10 justify-content-center">
            <div class="form-group row mt-4">
                <%= form.label :name, "Category name", class: "col-2 col-form-label text-light" %>
                <div class="col-10">
                    <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
                </div>
            </div>

            <div class="form-group mt-3 d-flex justify-content-around">
                <%= form.submit class: "btn btn-outline-light btn-lg" %>
            </div>
        <% end %>
        </div>
    </div>
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "d-flex justify-content-around text-info" %>
    </div>
</div>

app/views/categories/show.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Category: <%= @category.name %></h1>

    <% if logged_in? && current_user.admin? %>
        <div class="text-center mt-4">
            <%= link_to "Edit Category name", edit_category_path(@category), class: "btn btn-info" %>
        </div>
    <% end %>

    <h3 class="text-center mt-4">Articles</h3>

    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

    <%= render 'articles/article' %>

    <div class="flickr_pagination mb-4">
        <%= will_paginate @articles, :container => false %>
    </div>
</div>