config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  resources :articles
  resources :categories, except: [:delete]

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer id="stick-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Brock Bloomquist", "https://brockabloomquist.com", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show mb-0 shadow" role="alert">
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <li> <%= link_to "Create a new article", new_article_path, class: "dropdown-item" %> </li>
            <% end %>
            <li> <%= link_to "View Articles", articles_path, class: "dropdown-item" %> </li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
              <li> <%= link_to "Create a new Category", new_category_path, class: "dropdown-item" %> </li>
            <% end %>
            <li><%= link_to "View Categories", categories_path, class: "dropdown-item" %></li>
          </ul>
        </li>

        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %> [<%= "Admin " if current_user.admin? %>Profile]
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to "View your Profile", user_path(current_user), class: "dropdown-item" %> </li>
            <li> <%= link_to "Edit your Profile", edit_user_path(current_user), class: "dropdown-item" %> </li>
            <li> <%= button_to "Delete your Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { turbo_confirm: "Are you sure?" } %> </li>
          </ul>
        </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="d-flex flex-column" id="page-content">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>